* 100 Days of Clojure Code

** Day 21: October 5, 2018

I have a little fantasy that remains in the back of my mind, serving as inspiration for much of what I do.
The idea is tied to the practice of keeping configuration files on GitHub,
but in my case I want to take it to an extreme.

I want to be able to get a new computer and set up my whole environment with a single script.

It's a goal that started during my days of Linux distro-hopping,
but really has its roots in my earliest days of computing.
I just really love setting up new systems.
And every time that I do it, it (hopefully) becomes more streamlined.

Whether or not I ever achieve my goal of a single script, I do think it's worthwhile to keep in mind.

*** Codecademy - CSS course

Launched my [[https://porkostomus.gitlab.io/plain-html/][own instance]] of the Vacation World site
(for no good reason other than to practice deploying stuff).
Actually... it's so that I'm documenting my learning instead of doing it mindlessly,
and at the same time developing a "cookbook" of sorts.

Interesting... I just tried to duplicate what I did on GitHub,
and I can't figure out why the CSS is not loading [[https://porkostomus.github.io/vacation-world/][here]].

EDIT (following day): Now it works. Weird.

** Day 20
*** Successfully checked my gmail in spacemacs with mu4e and offlineimap

This could be an entire article of its own.
In fact, I wrote a tutorial on this last year, but it already broke from something changing.
It felt like a bit of a "right of passage" into emacs geekdom, kinda like installing Gentoo for Linux.

But here's the way I see it: 

**** Clojurians love emacs
It's still the most popular Clojure editor, right?

**** Those who love emacs, love to do lots of stuff in emacs

Like check our email.
As much satisfaction as I'd likely get from making this into a blog post,
it ought to be enough that the file .offlineimaprc is in my [[https://github.com/porkostomus/spacemacs-config][spacemacs-config]] repo.
I'll just add the instructions in the README to install offlineimap and mu4e.

As much as I'd love to include a screenshot

*** Having a fight with my browser tabs.

That is, having too many open. Feels like a sign that I'm trying to do too many things at once,
I'm trying to close tabs to get back to a reasonable number of tasks but everything seems important.
so... org-mode to the rescue! Let's break down the things I'm actively doing.

**** Codecademy - Web design courses

I used codecademy when I first started getting back into web stuff a few years ago.
Then, I read [[https://www.makeuseof.com/tag/4-reasons-shouldnt-learn-code-codeacademy/][4 Reasons Why You Shouldn’t Learn to Code With Codeacademy,]]
which explains that doing that stuff will teach you the syntax, but not how to solve problems.
That didn't make me stop using the site, but then I felt a little silly about it because I knew that the author was right.
The big win though from reading it was finding out about Project Euler,
which turned out to be a great help when I was first learning Clojure.

Now, however, I'm returning to them in order to combat another one of my fears:
Holes in my knowledge. I can never be ashamed to go back to the beginning.
I have a fear of becoming "one of those people" (in my imagination?)
whom I perceive as lacking a solid foundation due to insufficient time in the woodshed.

I refuse to develop for the web without properly understanding the basic web infrastructure.

So that's how I'm justifying spending time doing the basic codecademy courses again.
So that's a browser tab. And another one for a [[https://www.codecademy.com/learn/learn-navigation-design][pro-level course]] that I want to take while I've got a free week.
But not only that...

**** Set up a live HTML/CSS [[https://porkostomus.gitlab.io/plain-html/][playground site]] on GitLab

For just testing the codecademy practice sites!
I ought to do one on GitHub as well, just to keep everything familiar.

That's 2 tabs, for the source code and the site itself.

**** CircleCI

Just seems like it is important. So that's a browser tab.

More info - Here's the official stack listed on my job description:

Leiningen / deps.edn, Re-frame, Reagent and React’s lifecycles
REST and WebSockets
NodeJS, NPM and Yarn
JS / CLJS interop
CSS Preprocessors and mainstream CSS frameworks
Proper state management
UX principles and slick user interfaces
Data visualisation in SVG and Canvas

Experience with CI, Docker, AWS, Datomic Cloud and Ions is welcome.

So this is the list to keep handy, and will be used to form a solid study plan.

**** jr0cket's spacemacs book

This one is a very high priority. I should probably move this one up to indicate that.
But I need to learn org-mode...

**** Org-mode manual

See above.

**** Clojurians Slack

Always gotta have this open! Don't know what I'd do without the constant Clojure chatter!

That's actually all. I managed to close several while writing this (like twitter),
so it proved a valuable exercise. 

*** Now I need to look up the key binding in order to publish this!

I think it was a regular emacs binding like C-c C-e m or something...

Holy crap, I was right.

** Day 19
Yo, I'm in org mode. Today I'm doing stuff:

*** Codecademy stuff on UI design.

Did the HTML course just for the sake of completeness, and actually learned stuff.

*** Setting up spacemacs

One reason I love Clojure is because I only have one hand, and with Clojure you only need one!
Seriously... I doubt that any other language encourages such brevity -
one of Rich's reasons for choosing "nil" over "null" was "It's a little bit shorter"!
But with Clojure and Vim or Spacemacs Evil Mode, you only need one finger!

Got the cyberpunk theme with the nyan cat and fancy symbols!

*** Moved this journal into org mode

Yes, here we are. Isn't it beautiful?

Then, we can export to markdown. In fact, we can enable GitHub support in the config.

We're gonna need to follow [[http://spacemacs.org/layers/+emacs/org/README.html][this]]. (see that? that's a link, dawg)
